services:
  # React web frontend (Vite build served by Nginx)
  web:
    build:
      context: .
      dockerfile: Web_Frontend/Dockerfile
    image: web:latest
    ports:
      - 3000:3000
    networks:
      - project_network
    environment:
      - VITE_API_BASE=http://backend:8080
  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: backend:latest
    ports:
      - 8080:8080
    networks:
      - project_network
networks:
  project_network: